services:

  frontend:
    build: ./frontend/chat-app
    container_name: web-app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/chat-app/.env


  backend:
    build: ./backend
    container_name: express-api
    command: sh -c "npx prisma generate --schema=./prisma/schema.prisma && npm run dev"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules            
      - ./backend/uploads:/app/uploads


  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: